deploy:
  provider: releases
  api_key:
    secure: P+qpYsRXgB7QoMvqs6bWsw820G9rs+Ye6kSAbS5btEFH4enGgRbwHImc606gjQNEFEegLTCTe4hIMW8JaUmJ72Lze4KmiMJ6Bcis5C3Gd8XTdC9TJH9Xz0Qc4RYxe3vbOQX0Gl7zXSBXatuC+zztdrhAqI+OjopVW+qveDuxB0hgQS76GFB1yO/HdgCyDehMxFRopKFFMLUvt8LEMwrNjw/cnlwkr71//REV9PJ7PyCvrs3f5V2F9QPytaEU7l6ocUQmafGFJbAnqFcfyqfAd0g7iJmKNK5q9Tb4z1+Ree9cBxhLDP2SpzDqh93bNeUtWJpeLYvOf7WzFR0MYLtaUIu9ux61WNmAJuvzyJYrmhoQwgeTZeV2r2BtGx/90ChevknTc0A1fdUyb1zsOQ6IA6VVgAyhhc9c/FsdDZYamNUAeJvtvushCG8+WmKbnXhFPJF9rNCZPrGuLf8eUP0uoBAjIHExNPHKimHe09vWIvKfBmOtqOO0WgFHsd3Qt3YpFgmHWISfcY7Xd3FRDM5IYqVAjnb1oa3b0zR6I0ML9SiBHNXLMnlHEsdPj4bmdat48sZLBS/ym+o372QpRUlgV6I22F5zem4ltJEc2XwegFvP5iPYQEqtTLEhHZZY+UK2BQHmESN+DQP3o8g9Mrb+6YanL6UfFWAmWDGEsKPx6sA=
  file: log.txt
  on:
    repo: alanpoon/hardback_server
